# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bab1482a6fd14e7dd607a28c40f34499c322ef820dc6724887f8aa4f9c8fa0d59aa254ed1c53e98fb0ae5288314e21bc42e41baa81321e5c96b204602c767340

test:
  secret_key_base: 5b186558f4ed38089179b3e65f155e47a9e60eaece52d03a354a11702d36b76adff8074820fa4ee1fd06c3123aa5342241618816aab784abee74f3181a8d36c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
